### ISSUE TITLE
Add Python 3.7 to CI

### ISSUE THREAD

**Issue by cheind** [cheind/py-lapsolver#14]
we should also release binary wheels for Python 3.7 on Windows.

**Comment by sunxirui310** [comment]
environment: windows 10  and python 3.7

i've done below:
1.pip install source code . code path: "**H:\Demo\py-lapsolver\**"
2.use 'cmake cui' to generate  visual studio solution file and make project  on 'Release x64' mode  in "**H:\Demo\py-lapsolver\build**"
3.success to generate 3 files '**lapsolverc.cp37-win_amd64.pyd**' '**lapsolverc.exp**' '**lapsolverc.lib**' in path "**H:\Demo\py-lapsolver\build\Release**"
4. cmd "python setup.py develop" get  errors. 
`Traceback (most recent call last):
  File "setup.py", line 88, in <module>
    keywords='hungarian munkres kuhn linear-sum-assignment bipartite-graph lap'
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\develop.py", line 38, in run
    self.install_for_development()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 25, in run
    ", ".join(e.name for e in self.extensions))
RuntimeError: CMake must be installed to build the following extensions: lapsolverc`

what should I do next? 

thanks
