### ISSUE TITLE
Fails to install lapsolver using python 3.8

### ISSUE THREAD

**Issue by aminaghoul** [cheind/py-lapsolver#21]
I use Ubuntu and I tried to install lapsolver by doing what you wrote on the Readme page, but I got this error :

python3.8 setup.py develop
/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
WARNING: The wheel package is not available.
running develop
/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/command/develop.py:39: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing lapsolver.egg-info/PKG-INFO
writing dependency_links to lapsolver.egg-info/dependency_links.txt
writing top-level names to lapsolver.egg-info/top_level.txt
reading manifest file 'lapsolver.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.md'
adding license file 'LICENSE'
writing manifest file 'lapsolver.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "/mnt/data/home/aghoul/env8/bin/cmake", line 5, in <module>
    from cmake import cmake
ModuleNotFoundError: No module named 'cmake'
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    setup(
  File "/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/command/develop.py", line 33, in run
    self.install_for_development()
  File "/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/command/develop.py", line 108, in install_for_development
    self.run_command('build_ext')
  File "/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/mnt/data/home/aghoul/env8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 22, in run
    out = subprocess.check_output(['cmake', '--version'])
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.

Thank you for your response :+1:

**Comment by GabrielTruong** [comment]
Hi! 
Have you solved this issue by any chance ?

**Comment by cheind** [comment]
might be related to an outdated pybind11. could you try latest from master?
