### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by AxlJ** [cheind/py-lapsolver#5]
Hi, I get the following error installing the project on MacOS : 
axelpro:heetch_simulator $ pip install lapsolver
[...]
    [ 50%] Building CXX object CMakeFiles/lapsolverc.dir/src/lapsolverc.cpp.o
    clang: error: no such file or directory: 'NOTFOUND'
    make[2]: *** [CMakeFiles/lapsolverc.dir/src/lapsolverc.cpp.o] Error 1
    make[1]: *** [CMakeFiles/lapsolverc.dir/all] Error 2
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4p/jw6zpctd6sqd6hb7j_mz8fsh0000gp/T/pip-install-jsd4kq_g/lapsolver/setup.py", line 88, in <module>
        keywords='hungarian munkres kuhn linear-sum-assignment bipartite-graph lap'
      File "/anaconda3/envs/simu/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/anaconda3/envs/simu/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/anaconda3/envs/simu/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/anaconda3/envs/simu/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/anaconda3/envs/simu/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/anaconda3/envs/simu/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/anaconda3/envs/simu/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/anaconda3/envs/simu/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/anaconda3/envs/simu/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/anaconda3/envs/simu/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/anaconda3/envs/simu/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/4p/jw6zpctd6sqd6hb7j_mz8fsh0000gp/T/pip-install-jsd4kq_g/lapsolver/setup.py", line 33, in run
        self.build_extension(ext)
      File "/private/var/folders/4p/jw6zpctd6sqd6hb7j_mz8fsh0000gp/T/pip-install-jsd4kq_g/lapsolver/setup.py", line 58, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/anaconda3/envs/simu/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.

**Comment by cheind** [comment]
hmm not sure what this error means. Seems like clang cannot find a specific directory.

**Comment by kennethdamica** [comment]
I had the same problem. My solution is below. Let me know if this works for you because I tried a few other things before this that could have had an effect. 

brew install llvm
brew install libomp
ln -s /usr/local/opt/llvm/bin/clang /usr/local/bin/clang-omp
ln -s /usr/local/opt/llvm/bin/clang++ /usr/local/bin/clang-omp++
export DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include"
export DOpenMP_CXX_LIB_NAMES="omp"
export DOpenMP_omp_LIBRARY=/usr/local/opt/libomp/lib/libomp.dylib

**Comment by suxuann** [comment]
I am having the same issue. Do you know how to solve this problem?

**Comment by cheind** [comment]
Sorry I don't have access to a mac os currently.
